connector.name=iceberg
iceberg.catalog.type=REST
iceberg.rest-catalog.uri=http://polaris:8181/api/catalog
iceberg.rest-catalog.credential=admin:admin123
iceberg.rest-catalog.warehouse=kyc-lakehouse
iceberg.rest-catalog.prefix=kyc
iceberg.file-format=PARQUET
iceberg.compression-codec=ZSTD
iceberg.target-file-size=256MB
iceberg.minimum-assigned-split-weight=0.05
iceberg.table-statistics-enabled=true
iceberg.projection_pushdown_enabled=true
iceberg.unique-table-location=false
iceberg.sort-order-layout-enabled=true
iceberg.register-table-procedure-enabled=true
iceberg.query-partition-filter-required=false
iceberg.max-partitions-per-writer=100
iceberg.hive-catalog-name=
