connector.name=postgresql
connection-url=jdbc:postgresql://postgres:5432/kyc_vault
connection-user=trino
connection-password=${ENV:TRINO_POSTGRES_PASSWORD}
connection-pool-max-size=20
connection-pool-min-size=8
case-insensitive-name-matching=true
postgresql.domain-compaction-threshold=100
metadata.cache-ttl=30s
metadata.cache-missing=true
allow-drop-table=false
aggregate-pushdown=true
join-pushdown=true
topn-pushdown=true
