replicaCount: 1

image:
  repository: ghcr.io/quantumworld-dpdns-io/kyc-vault
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 3000

resources:
  limits:
    cpu: "2"
    memory: 4Gi
  requests:
    cpu: "500m"
    memory: 1Gi

postgresql:
  enabled: true
  auth:
    database: kyc_vault

redis:
  enabled: true
  auth:
    enabled: false
