coordinator=true
node-scheduler.include-coordinator=false
discovery-server.enabled=true
discovery.uri=http://localhost:8080
http-server.http.port=8080
query.max-memory=16GB
query.max-memory-per-node=4GB
query.max-total-memory-per-node=8GB
query.max-run-time=30m
query.max-execution-time=20m
query.min-expire-age=10m
query.max-history=1000
query.client.timeout=10m
memory.heap-headroom-per-node=2GB
task.max-worker-threads=16
task.concurrency=16
task.default-concurrency=16
task.writer-count=4
exchange.http-client.max-connections=500
exchange.http-client.max-connections-per-server=50
sink.max-buffer-size=32MB
sink.max-partitions-per-writer=100
analyzer.experimental-syntax-enabled=true
optimizer.optimize-hash-generation=true
optimizer.optimize-metadata-queries=true
optimizer.optimize-single-distinct=true
optimizer.dict-min-group-size-bits=10
distributed-sort-enabled=true
join-distribution-type=AUTOMATIC
experimental.resource-groups-enabled=true
resource-group.config-manager=file
resource-groups.config-file=etc/resource-groups.json
