apiVersion: v1
kind: ResourceQuota
metadata:
  name: kyc-vault-quota
  namespace: kyc-vault
  labels:
    app.kubernetes.io/name: kyc-vault
    app.kubernetes.io/component: resource-quota
spec:
  hard:
    requests.cpu: "32"
    requests.memory: "128Gi"
    limits.cpu: "64"
    limits.memory: "256Gi"
    persistentvolumeclaims: "20"
    services.loadbalancers: "5"
    count/ingresses.extensions: "3"
